# Generated by Django 3.2.3 on 2022-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
